# templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # Use .Release.Name instead of the missing helper template
  name: {{ .Release.Name }}
  labels:
    # Strictly required for the Prometheus Operator to discover the target
    release: prom-stack
spec:
  selector:
    matchLabels:
      # Must match the Service labels for the ServiceMonitor to discover it
      {{- include "kube-prober.selectorLabels" . | nindent 6 }} 
  endpoints:
    - port: metrics
      interval: 2s
      path: /metrics

