{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    # Prometheus Operator discovery label
    release: {{ .Values.serviceMonitor.releaseLabel | default "prom-stack" }}
    {{- include "kube-prober.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-prober.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 2s
      path: /metrics
{{- end }}