apiVersion: v2
name: kube-prober
description: Helm chart for the Kube Prober
type: application
version: 1.0.1
appVersion: "1.0.1"
icon: https://raw.githubusercontent.com/demirdilek/kube-prober/main/assets/pods.png