# Replica count for the prober
replicaCount: 1

# Image configuration for the prober
image:
  repository: ghcr.io/demirdilek/kube-prober
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

# Service configuration for the prober
service:
  type: ClusterIP
  port: 8080

# Resource requests and limits for the prober container
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# PodDisruptionBudget configuration
pdb:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# HorizontalPodAutoscaler configuration
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# TopologySpreadConstraints configuration
topologySpreadConstraints:
  enabled: true
  whenUnsatisfiable: ScheduleAnyway

env:
  TLS_INSECURE_SKIP_VERIFY: "false" # Secure production default